spring:
    application:
        name: TheatreMongo
    mvc:    
        hiddenmethod:
            filter:
                enabled: true
mongodb:
    connection:
        database: theatre
        host: mongodb
        port: 27017
logging:
    level:
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG


